version: "3.9"

services:
    demarket-database:
        container_name: demarket-database
        image: postgres:12
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: demarket-database
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
